from playwright.sync_api import sync_playwright
import time
import asyncio
import sys

def execute_test_plan(actions: list[dict]):
    """
    Executes a list of Playwright actions using sync_playwright.
    
    Args:
        actions (list[dict]): The list of actions generated by the AI agent.
    """
    # Fix for Windows: Ensure ProactorEventLoop is used for subprocesses
    if sys.platform == 'win32':
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

    print("Starting test execution...")
    with sync_playwright() as p:
        # Launch Chromium in headful mode with slow_mo to visualize actions
        browser = p.chromium.launch(headless=False, slow_mo=1000)
        page = browser.new_page()
        
        try:
            for i, action_item in enumerate(actions):
                act_type = action_item.get("action")
                selector = action_item.get("selector")
                value = action_item.get("value")
                
                print(f"Step {i+1}: {act_type} -> {selector} ({value})")
                
                if act_type == "navigate":
                    if value:
                        page.goto(value)
                    else:
                        print("Warning: 'navigate' action missing URL.")

                elif act_type == "click":
                    if selector:
                        locator = page.locator(selector)
                        
                        # Inject Red Halo Effect (lasts 5 seconds)
                        locator.evaluate("""(el) => {
                            const originalBoxShadow = el.style.boxShadow;
                            el.style.boxShadow = '0 0 15px 5px red';
                            el.style.transition = 'box-shadow 0.3s ease-in-out';
                            setTimeout(() => {
                                el.style.boxShadow = originalBoxShadow;
                            }, 5000);
                        }""")
                        
                        # Optional: Short pause to ensure the user sees the halo before the click happens
                        time.sleep(0.5)
                        
                        locator.click()
                    else:
                        print("Warning: 'click' action missing selector.")

                elif act_type == "type":
                    if selector and value:
                        locator = page.locator(selector)
                        locator.highlight()
                        locator.fill(value)
                    else:
                        print("Warning: 'type' action missing selector or value.")

                elif act_type == "assert_text":
                    if selector and value:
                        locator = page.locator(selector)
                        locator.highlight()
                        # Wait for element to be visible
                        locator.wait_for(state="visible", timeout=5000)
                        
                        # Check text content
                        text_found = locator.text_content() or ""
                        if value in text_found:
                            print(f"Assertion Passed: Found '{value}' in element.")
                        else:
                            raise AssertionError(f"Expected text '{value}' not found in element '{selector}'. Found: '{text_found}'")
                    else:
                        print("Warning: 'assert_text' action missing selector or value.")
                
                else:
                    print(f"Unknown action type: {act_type}")

            print("Test execution completed successfully!")
            time.sleep(2) # Keep open briefly to see final state

        except Exception as e:
            print(f"Test execution failed: {str(e)}")
            time.sleep(5) # Keep open longer on error for debugging
        finally:
            browser.close()
